### ISSUE TITLE
FR: Return debugging information from failures

### ISSUE THREAD

**Issue by samtstern** [GitbookIO/expect-firestore#3]
When access fails I'd love to get more than `false`.  Would be good to get the full API response so that I can find unexpected errors or make sure that the error is of the kind I expected.

**Comment by samtstern** [comment]
Actually it doesn't even look like the extra information is getting to `expect-firestore` ... which is strange.

Request:
```
{
  "name": "projects/firestore-snippets",
  "resource": {
    "source": {
      "files": [
        {
          "name": "firestore.rules",
          "content": "service cloud.firestore {\n  match /databases/{database}/documents {\n    match /{document=**} {\n      allow read, write;\n    }\n  }\n}\n"
        }
      ]
    },
    "testSuite": {
      "testCases": [
        {
          "expectation": "ALLOW",
          "request": {
            "auth": {
              "uid": "user123"
            },
            "path": "/databases/(default)/documents/stories/story1",
            "method": "post"
          },
          "resource": {},
          "functionMocks": [
            {
              "function": "get",
              "args": [
                {
                  "exact_value": "stories/story1"
                }
              ],
              "result": {
                "value": {
                  "data": {
                    "name": "Story 1"
                  }
                }
              }
            },
            {
              "function": "exists",
              "args": [
                {
                  "exact_value": "stories/story1"
                }
              ],
              "result": {
                "value": {
                  "data": true
                }
              }
            }
          ]
        }
      ]
    }
  }
}
```

Response
```
{ testResults: [ { state: 'FAILURE' } ] }
```

So I am wondering if I am doing something wrong.  But either way it would be useful for this library to expose the whole object rather than doing a check on `testResults[0].state`

**Comment by samtstern** [comment]
(Deleted my previous comment, that's a different bug)

Here's an example of some good info I get from a failure by inserting some `console.log` statements inside the library:

```
{
  "testResults": [
    {
      "state": "FAILURE",
      "debugMessages": [
        "Error: firestore.rules line [9], column [18]. Property data is undefined on object."
      ],
      "errorPosition": {
        "fileName": "firestore.rules",
        "line": 9,
        "column": 18
      }
    }
  ]
}
```

**Comment by SamyPesse** [comment]
I agree, it'd be nice to have the testing methods return an instance of a `Result` class with a method `.toString()` to get it as human readable version. It could help debug assertions.

Similar to what [`targaryen`](https://github.com/goldibex/targaryen) is doing for the RTDB with [`targaryen.util.readableError`](https://github.com/goldibex/targaryen/blob/master/plugins/jasmine.js#L46), etc

Since we are not using Firestore at the moment, and are actually considering switching to AWS and AWS AppSync, I don't have much time to invest in this library at the moment.

But PRs are welcome :)

**Comment by samtstern** [comment]
Thanks @SamyPesse, I think I'll send over some PRs then!  

Also if you have the time, I'd love if you could email me and let me know what's motivating you to switch to AppSync.  I promise I won't try to change your mind, just genuinely curious for the feedback.
