### ISSUE TITLE
Function mocks for get() and exists() need to pass absolute paths

### ISSUE THREAD

**Issue by samtstern** [GitbookIO/expect-firestore#6]
Function mocks need to make sure to use the full `/databases/` path:

```js
function: "get",
args: [{ exact_value: "/databases/(default)/documents/" + path }],
result: {
  value: {
     // ...
   }
}
```

(note @SamyPesse I am filing these as I find them, I will try and find time to fix them myself)

**Comment by samtstern** [comment]
It actually looks like that is the case here:
https://github.com/GitbookIO/expect-firestore/blob/3069c2094a93b548193aca65c54b5985364c2dd2/src/database.js#L269

@SamyPesse is it possible the release version on `npm` is older than the code here>

**Comment by SamyPesse** [comment]
The code on NPM doesn't include https://github.com/GitbookIO/expect-firestore/commit/3069c2094a93b548193aca65c54b5985364c2dd2

A release is published for each commits `Bump version to X 🚀`: https://github.com/GitbookIO/expect-firestore/commits/master

**Comment by samtstern** [comment]
Ah cool.  Also i see where the problem is, PR incoming.
